apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: chatbot-backend
    newName: ghcr.io/vishnuvteja/chatbot-backend
    newTag: cbae10999c0b630c3710fe6fd3908d0dd93f4134
  - name: chatbot-frontend
    newName: ghcr.io/vishnuvteja/chatbot-frontend
    newTag: cbae10999c0b630c3710fe6fd3908d0dd93f4134
