apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: chatbot-backend
    newName: ghcr.io/vishnuvteja/chatbot-backend
    newTag: 21a3f946fbf70d20eadfa15d26a299f5967732e5
  - name: chatbot-frontend
    newName: ghcr.io/vishnuvteja/chatbot-frontend
    newTag: 21a3f946fbf70d20eadfa15d26a299f5967732e5
