apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: ingress-traefik.yaml
images:
  - name: replace-me-backend
    newName: ghcr.io/YOUR_GITHUB_OWNER/chatbot-backend
    newTag: latest
  - name: replace-me-frontend
    newName: ghcr.io/YOUR_GITHUB_OWNER/chatbot-frontend
    newTag: latest
